### ISSUE TITLE
Action doesn't find ruleset

### ISSUE THREAD

**Issue by rsoesemann** [pmd/pmd-github-action#117]
No matter what I put into my action 
https://github.com/rsoesemann/salesforce-recipes/runs/7668564645?check_suite_focus=true

as [ruleset.xml ](https://github.com/rsoesemann/salesforce-recipes/blob/master/ruleset.xml)path 

 - 'ruleset.xml'
 - '/ruleset.xml'
 - './ruleset.xml'

I always get the same error:

> WARNING: No rules found. Maybe you misspelled a rule name? (./ruleset.xml)
> PMD exited with 1
> Error: Unexpected end of JSON input

**Comment by Jivyx** [comment]
Your step do not checkout the project, so yes, the ruleset is not present

**Comment by adangel** [comment]
Yes, the checkout step was missing.
