### ISSUE TITLE
Action aborts with: Error: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by rsoesemann** [pmd/pmd-github-action#127]
When I created a PR with an Apex change the PMD Github Action aborted with this 

[analyze](https://github.com/rsoesemann/salesforce-recipes/actions/runs/3103854883/jobs/5027646879#step:4:34)
Cannot read property 'split' of undefined

Looks like it aborted after parsing the SARIF of the second issue. At least only one is displayed correctly

**Comment by adangel** [comment]
We call split here: https://github.com/pmd/pmd-github-action/blob/76f6e255c0d5fba5f3182825af0ecf11c687fa71/lib/annotations.js#L55

I think, this problem occurs if a rule has no description... the action should however not abort, if this is the case.
