### ISSUE TITLE
Please publish newer version using node20 you made 2 months ago. Latest version is +10 months stale.   Lots of stuff has been added since

### ISSUE THREAD

**Issue by wac84s** [pmd/pmd-github-action#264]
Please publish newer version using node20 you made 2 months ago.  Latest version is +10 months stale.   Lots of stuff has been added since

https://github.com/pmd/pmd-github-action/tree/v1.4.1

Related issues:

* #221
* #253

**Comment by adangel** [comment]
Can you test, whether `uses: pmd/pmd-github-action@2f4fec3feaff3a32082ae90daa83f16a5727522d` works? That would be the latest version from current main branch (2f4fec3feaff3a32082ae90daa83f16a5727522d).

**Comment by adangel** [comment]
This is done now: https://github.com/pmd/pmd-github-action/releases/tag/v2.0.0
